### ISSUE TITLE
Doesn't run against skimage anymore

### ISSUE THREAD

**Issue by behdad** [simoncozens/atokern#7]
```
$ ./kerncritic ~/hb/Roboto-Regular.ttf
Traceback (most recent call last):
  File "/home/behdad/kerning/atokern/./kerncritic", line 8, in <module>
    from tensorfont import Font
  File "/home/behdad/.local/lib/python3.11/site-packages/tensorfont/__init__.py", line 7, in <module>
    from skimage.util import pad
ImportError: cannot import name 'pad' from 'skimage.util' (/home/behdad/.local/lib/python3.11/site-packages/skimage/util/__init__.py)
```

```
Requirement already satisfied: scikit-image in /home/behdad/.local/lib/python3.11/site-packages (0.21.0)
```

**Comment by simoncozens** [comment]
Upgrade tensorfont to 0.1.0

**Comment by behdad** [comment]
> Upgrade tensorfont to 0.1.0

Thanks. Can you publish to pip?

**Comment by behdad** [comment]
Humm. Didn't help. The import is right there in `kerncritic` itself.
